# Generated by Django 4.0.3 on 2022-06-19 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0002_alter_salesperson_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesperson',
            name='sales',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='salesperson', to='sales_rest.salesrecord'),
        ),
    ]
