# Generated by Django 4.0.3 on 2022-06-19 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0003_alter_salesperson_sales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesperson',
            name='sales',
        ),
        migrations.AddField(
            model_name='salesperson',
            name='sales',
            field=models.ManyToManyField(blank=True, null=True, related_name='salesperson', to='sales_rest.salesrecord'),
        ),
    ]
