# Generated by Django 4.0.3 on 2022-06-19 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0004_remove_salesperson_sales_salesperson_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesperson',
            name='sales',
            field=models.ManyToManyField(blank=True, related_name='salesperson', to='sales_rest.salesrecord'),
        ),
    ]
