# Generated by Django 4.0.3 on 2022-06-19 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0005_alter_salesperson_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='automobilevo',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='automobilevo',
            name='is_sold',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
