# Generated by Django 4.0.3 on 2022-06-19 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0006_automobilevo_name_alter_automobilevo_is_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesperson',
            name='sales',
            field=models.ManyToManyField(blank=True, to='sales_rest.salesrecord'),
        ),
    ]
