# Generated by Django 4.0.3 on 2022-06-20 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0007_alter_salesperson_sales'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesrecord',
            old_name='automobile',
            new_name='automobilevin',
        ),
    ]
