# Generated by Django 4.0.3 on 2022-06-20 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0008_rename_automobile_salesrecord_automobilevin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesrecord',
            old_name='automobilevin',
            new_name='automobile',
        ),
    ]
