# Generated by Django 4.0.3 on 2022-06-22 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0007_alter_automobilevo_vin_alter_service_vin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'statuses',
            },
        ),
        migrations.AddField(
            model_name='automobilevo',
            name='color',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='automobilevo',
            name='model',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='automobilevo',
            name='vip',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='automobilevo',
            name='year',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='services', to='service_rest.status'),
        ),
    ]
